version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: weekly
      time: "14:00"
      timezone: Asia/Seoul
    reviewers:
      - Ohzzi
      - jayjaehunchoi
      - jinyoungchoi95
