version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: daily
      time: "14:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    reviewers:
      - Ohzzi
      - jayjaehunchoi
      - jinyoungchoi95
